import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import AppNav from "@/components/navigation/app-navbar";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Snap Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "max-w-7xl",
        "mx-auto",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        "md:px-6",
        "lg:px-8",
        geist.variable,
      )}
    >
      <body className="">
        <AppNav />
        {children}
      </body>
    </html>
  );
}
